version: "3.3"

services:
  db:
    image: mariadb:10.1.44
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - ./app:/usr/src/app
    user: ${LOCAL_USER}
    environment:
      DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}?serverVersion=mariadb-10.1.44
      APP_ENV: ${ENV}

  yarn:
    image: node:10
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    user: ${LOCAL_USER}
    stdin_open: true

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - ${ADMINER_PORT}:8080

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - ./app/public/:/usr/src/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php
