version: "3.3"

services:
  db:
    image: mariadb:10.1.44
    restart: on-failure
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - ${ADMINER_PORT}:8080

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - ./app/public/:/usr/src/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php

  # Utils
  composer:
    image: composer:1.9.3
    restart: "no"
    volumes:
      - ./app:/app
    user: ${LOCAL_USER}
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}?serverVersion=mariadb-10.1.44
      APP_ENV: ${ENV}

  node:
    image: node:10
    volumes:
      - ./app:/home/node/app
    working_dir: /home/node/app
    user: ${LOCAL_USER}

  
